name: pfd
description: Primary Flight Display Widget that supports Roll, Pitch, Yaw, Airspeed and Altitude.
version: 0.0.4
homepage: https://github.com/nirex0/pfd
issue_tracker: https://github.com/nirex0/pfd/issues

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
